### ISSUE TITLE
[TODO] Допилка контактов

### ISSUE THREAD

**Issue by veselcraft** [mrimsu/mrim-server#28]
- [x] Проверяется добавил ли его контакт в ответ
- [x] Ему сразу передаётся статус юзера
- [x] Контакт удаляется из базы данных НА САМОМ ДЕЛЕ
- [x] При удалении контакта пользователем, которого добавили, меняется местами `adder_user_id`, `contact_user_id`, и ему подобные значения
- [x] При удалении контакста пользователь уходит в оффлайн или `STATUS_UNDETERMINATED` (0x03)
